import { API, parseRelease } from '../lib/releases.mjs';
const theme=document.querySelector<HTMLButtonElement>('.theme-toggle');
if(theme) { theme.hidden=false; theme.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('mm-client-theme',next);}catch{}}); }
for(const link of document.querySelectorAll<HTMLAnchorElement>('[data-language]')) link.addEventListener('click',()=>{try{localStorage.setItem('mm-client-language',link.dataset.language!);}catch{}if(link.dataset.language==='ru')link.href=new URL('/spk-mm-client/?lang=ru',location.origin).href;});
const tabs=[...document.querySelectorAll<HTMLButtonElement>('[role=tab]')];
const panels=[...document.querySelectorAll<HTMLElement>('[data-gallery-panel]')];
function select(at:number){tabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===at));t.tabIndex=i===at?0:-1;});panels.forEach((p,i)=>p.hidden=i!==at);}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>select(i));tab.addEventListener('keydown',e=>{const next=e.key==='ArrowRight'?(i+1)%tabs.length:e.key==='ArrowLeft'?(i+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(next!==null){e.preventDefault();select(next);tabs[next].focus();}});});
const host=document.querySelector<HTMLElement>('[data-downloads]');
if(host) {const labels=JSON.parse(host.dataset.labels!);const status=host.querySelector<HTMLElement>('[data-release-status]')!;const files=host.querySelector<HTMLElement>('[data-packages]')!;status.textContent=labels.loading;const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),8000);
void (async()=>{try{const response=await fetch(API,{signal:abort.signal});if(response.status===404){status.textContent=labels.none;return;}if(!response.ok)throw Error('release unavailable');const release=parseRelease(await response.json());if(!release?.files.length){status.textContent=labels.none;return;}status.textContent=labels.release+' '+release.version;files.hidden=false;for(const file of release.files){const row=document.createElement('article');row.className='package';const name=document.createElement('strong');name.textContent=file.name;const link=document.createElement('a');link.href=file.browser_download_url;link.textContent=labels.download;row.append(name,link);if(file.checksum){const checksum=document.createElement('a');checksum.href=file.checksum;checksum.textContent='SHA-256';row.append(checksum);}files.append(row);}}catch{status.textContent=labels.unavailable;}finally{clearTimeout(timer);}})();}
