// Guards the UI pass's Ruling ("Иконки"): any glyph serving as an icon in a
// button/link/chip/list row/badge goes through components/icons.tsx, not a
// raw emoji/dingbat/arrow character. Scans every .ts/.tsx file under
// frontend/src (not just components/*.tsx — fix round 1, controller
// finding on f13caf3: components/glyph.ts's channel-type markers were UI
// icons too, and were missed because the original glob only covered
// components/*.tsx). Real emoji are unaffected: EmojiGlyph.tsx computes
// its glyph at runtime (no matching literal in its own source, so it needs
// no allowlist entry), and frontend/src/emoji/ (the generated emoji
// dataset and its lookup code, scripts/gen-emoji.mjs) is excluded below —
// glyph.ts no longer exists (channel-type markers moved into icons.tsx as
// IconLock/IconGroup/IconHash/ChannelTypeMarker).
//
// Ranges (deliberately the same ones the plan's Ruling names, not a wider
// net): U+1F300–U+1FAFF (emoji), U+2190–U+21FF (arrows), U+2300–U+23FF
// (misc technical), U+25A0–U+25FF (geometric shapes), U+2700–U+27BF
// (dingbats).
const ICON_RANGES = /[\u{1F300}-\u{1FAFF}\u{2190}-\u{21FF}\u{2300}-\u{23FF}\u{25A0}-\u{25FF}\u{2700}-\u{27BF}]/u

// Path-based exceptions, each with its reason. Test files intentionally
// keep real emoji in expected strings (reaction/channel-marker assertions)
// and may use a glyph in a descriptive test title; neither is UI source.
// frontend/src/emoji/ is the real emoji dataset (generated by
// scripts/gen-emoji.mjs) and its lookup helpers — real emoji, not icons.
const ALLOW: { match(path: string): boolean; reason: string }[] = [
  { match: (p) => p.includes('.test.'), reason: 'tests assert on real emoji (reactions, channel markers) and may name a glyph in a title; not UI source' },
  { match: (p) => p.includes('/emoji/'), reason: 'the real emoji dataset and its lookup code, not UI icons' },
]

// Strips /* */ and // comments so only JSX text and string literals remain
// (this codebase's non-test, non-emoji sources have no "//" inside string
// literals to trip on — verified before widening this scan).
function stripComments(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '')
}

test('no emoji/dingbat/arrow glyph stands in for an icon anywhere in frontend/src', () => {
  const files = import.meta.glob('../**/*.{ts,tsx}', { eager: true, query: '?raw', import: 'default' }) as Record<string, string>
  const offenders = Object.entries(files)
    .filter(([path]) => !ALLOW.some((a) => a.match(path)))
    .filter(([, text]) => ICON_RANGES.test(stripComments(text)))
    .map(([path]) => path)
  expect(offenders).toEqual([])
})
