// Guards the UI pass's Ruling ("Иконки"): any glyph serving as an icon in a
// button/link/chip/list row/badge goes through components/icons.tsx, not a
// raw emoji/dingbat/arrow/symbol character. Scans every .ts/.tsx file under
// frontend/src (not just components/*.tsx — fix round 1, controller
// finding on f13caf3: components/glyph.ts's channel-type markers were UI
// icons too, and were missed because the original glob only covered
// components/*.tsx). Real emoji are unaffected: EmojiGlyph.tsx computes
// its glyph at runtime (no matching literal in its own source, so it needs
// no allowlist entry), and frontend/src/emoji/ (the generated emoji
// dataset and its lookup code, scripts/gen-emoji.mjs) is excluded below —
// glyph.ts no longer exists (channel-type markers moved into icons.tsx as
// IconLock/IconGroup/IconHash/ChannelTypeMarker).
//
// Ranges (fix round 2, controller RULING: widened past the plan's original
// five ranges — this task also touched/missed glyphs those five don't
// cover, e.g. × in AttachmentsTray's remove chip, ‹ › in Viewer/TextView's
// prev/next, ⋯ in Sidebar's menu button, ⬇ in several download buttons, ⤢
// in expand buttons, ☺ in the reaction-add chip; all now fixed, but the
// guard needs the wider net to actually catch a regression):
// U+00D7 (×), U+2039/U+203A (‹ ›), U+2190–U+21FF (arrows), U+22EF (⋯),
// U+2300–U+23FF (misc technical), U+25A0–U+25FF (geometric shapes),
// U+2600–U+26FF (misc symbols, incl. ☺ U+263A), U+2700–U+27BF (dingbats),
// U+2900–U+297F (supplemental arrows-B, incl. ⤢ U+2922), U+2B00–U+2BFF
// (misc symbols/arrows, incl. ⬇ U+2B07), U+1F300–U+1FAFF (emoji).
const ICON_RANGES =
  /[\u{00D7}\u{2039}\u{203A}\u{2190}-\u{21FF}\u{22EF}\u{2300}-\u{23FF}\u{25A0}-\u{25FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{2900}-\u{297F}\u{2B00}-\u{2BFF}\u{1F300}-\u{1FAFF}]/u

// Path-based exceptions, each with its reason. Test files intentionally
// keep real emoji in expected strings (reaction/channel-marker assertions)
// and may use a glyph in a descriptive test title; neither is UI source.
// frontend/src/emoji/ is the real emoji dataset (generated by
// scripts/gen-emoji.mjs) and its lookup helpers — real emoji, not icons.
//
// No other exceptions exist today: a repo-wide grep for every character in
// ICON_RANGES, outside comments/tests/emoji/, found none (e.g. no
// "1920×1080"-style size label uses × as text) — if one is added later,
// add a narrow match() here with its reason, not a hole in the ranges.
const ALLOW: { match(path: string): boolean; reason: string }[] = [
  { match: (p) => p.includes('.test.'), reason: 'tests assert on real emoji (reactions, channel markers) and may name a glyph in a title; not UI source' },
  { match: (p) => p.includes('/emoji/'), reason: 'the real emoji dataset and its lookup code, not UI icons' },
]

// Strips // and /* */ comments while leaving string/template literal
// content untouched — a naive `.replace(/\/\/.*/, '')` would wrongly treat
// a "//" inside a string (e.g. a "http://…" URL) as the start of a
// comment and silently drop the rest of that line (fix round 2, controller
// RULING). This is a small hand-rolled scanner, not a full JS/TS parser:
// it tracks only "am I inside a quoted string right now", which is enough
// to tell a real `//`/`/*` from one that merely appears inside a string;
// it does not parse regex literals (none of this codebase's non-test,
// non-emoji sources contain a `/…/` regex literal with a `//` or `/*`
// inside it — verified by inspection).
function stripComments(src: string): string {
  let out = ''
  let i = 0
  const n = src.length
  while (i < n) {
    const c = src[i]
    const c2 = src[i + 1]
    if (c === '/' && c2 === '/') {
      i += 2
      while (i < n && src[i] !== '\n') i++
      continue
    }
    if (c === '/' && c2 === '*') {
      i += 2
      while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i++
      i = Math.min(i + 2, n)
      continue
    }
    if (c === '"' || c === "'" || c === '`') {
      const quote = c
      out += c
      i++
      while (i < n && src[i] !== quote) {
        if (src[i] === '\\' && i + 1 < n) {
          out += src[i] + src[i + 1]
          i += 2
          continue
        }
        out += src[i]
        i++
      }
      if (i < n) {
        out += src[i]
        i++
      }
      continue
    }
    out += c
    i++
  }
  return out
}

test('no emoji/dingbat/arrow/symbol glyph stands in for an icon anywhere in frontend/src', () => {
  const files = import.meta.glob('../**/*.{ts,tsx}', { eager: true, query: '?raw', import: 'default' }) as Record<string, string>
  const offenders = Object.entries(files)
    .filter(([path]) => !ALLOW.some((a) => a.match(path)))
    .filter(([, text]) => ICON_RANGES.test(stripComments(text)))
    .map(([path]) => path)
  expect(offenders).toEqual([])
})

test('stripComments keeps a "//" inside a string literal instead of treating it as a comment', () => {
  const src = 'const url = "http://example.com/x" // real comment with × in it\nconst kept = "b"'
  const out = stripComments(src)
  expect(out).toContain('http://example.com/x')
  expect(out).not.toContain('real comment')
  expect(out).not.toContain('×')
  expect(out).toContain('const kept = "b"')
})
