import { expect, test } from '@playwright/test'
import { apiCall, channel, removeServerFromMenu, signInAlice, threadComposer, threadPane, threadFeed, seedThread, rootRow, scrollUntilVisible } from './helpers'
import { mkdirSync } from 'node:fs'
import { join } from 'node:path'

const captures = process.env.SPK_MM_SITE_CAPTURES
if (captures) mkdirSync(captures, { recursive: true })

test('About is visible before sign-in and preserves the live chat, draft and focus', async ({ page, context }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'About', exact: true })
  await expect(trigger).toBeVisible()
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'About SPK MM Client' })
  const info = await apiCall(page,'AppInfo')
  await expect(dialog).toContainText(info.version)
  await expect(dialog).not.toContainText('Citeck')
  await expect(dialog.getByRole('link',{name:'Apache License 2.0'})).toHaveAttribute('href','https://github.com/Sipaha/spk-mm-client/blob/main/LICENSE')
  await expect(dialog.getByRole('button', { name:'Close', exact:true })).toBeFocused()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('link',{ name:'About the author' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await signInAlice(page)
  const feed = page.locator('[data-feed="channel"]')
  const original = await feed.elementHandle()
  const composer = page.getByRole('textbox',{ name:'Message' }).first()
  await composer.fill('Unsent draft retained while reading About')
  await trigger.click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('link',{name:'Product website'})).toHaveAttribute('href','https://sipaha.github.io/spk-mm-client/en/')
  await context.route('https://sipaha.github.io/**',r=>r.fulfill({contentType:'text/html',body:'<title>Isolated link fixture</title>'}))
  const popup = page.waitForEvent('popup')
  await dialog.getByRole('link',{ name:'About the author' }).click()
  const opened = await popup
  await opened.waitForURL('https://sipaha.github.io/about/en/')
  await opened.close()
  for (const width of [860,1280]) {
    await page.setViewportSize({width,height:800})
    expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
    if (captures) await page.screenshot({path:join(captures,`about-en-${width}.png`)})
  }
  await page.keyboard.press('Escape')
  await expect(composer).toHaveValue('Unsent draft retained while reading About')
  expect(await feed.evaluate((el,before)=>el===before,original)).toBe(true)
  const root = feed.locator('[data-post-id]').last()
  await root.scrollIntoViewIfNeeded()
  await expect(root).toBeInViewport({ ratio: 1 })
  await root.hover()
  await root.getByRole('button', { name: 'Reply in thread' }).click()
  await expect(threadComposer(page)).toBeVisible()
  await threadComposer(page).fill('Unsent thread reply retained')
  const threadBefore = await threadPane(page).elementHandle()
  const scrollBefore = await feed.evaluate(el => el.scrollTop)
  await trigger.click()
  await expect(dialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(threadComposer(page)).toHaveValue('Unsent thread reply retained')
  await expect(composer).toHaveValue('Unsent draft retained while reading About')
  expect(await threadPane(page).evaluate((el,before) => el === before, threadBefore)).toBe(true)
  expect(await feed.evaluate(el => el.scrollTop)).toBe(scrollBefore)
  await expect(trigger).toBeFocused()
  await threadComposer(page).fill('')
  await threadPane(page).getByRole('button', { name: 'Close thread' }).click()
  await composer.fill('')
  if (captures) {
    await page.setViewportSize({width:1440,height:900})
    const demo = 'Design review: keep the conversation and its files together.'
    await seedThread(page, demo, ['The PDF preview is ready to review.', 'Thanks. I will add notes in this thread.'])
    const post = rootRow(page, demo)
    await expect.poll(async () => {
      await feed.evaluate(el => el.scrollTo({ top: el.scrollHeight }))
      return post.count()
    }).toBe(1)
    await post.scrollIntoViewIfNeeded()
    await page.screenshot({path:join(captures,'chat-en.png')})
    await post.hover()
    await post.getByRole('button',{name:'Reply in thread'}).click()
    await expect(threadComposer(page)).toBeVisible()
    await expect(threadFeed(page).getByText('Thanks. I will add notes in this thread.', { exact: true })).toBeVisible()
    await page.screenshot({path:join(captures,'threads-en.png')})
    await threadPane(page).getByRole('button',{name:'Close thread'}).click()
    await channel(page,'Off-Topic').click()
    await expect(page.getByRole('heading', { name: 'Off-Topic', exact: true })).toBeVisible()
    const file = feed.getByRole('button', { name: 'View manual.pdf', exact: true })
    await scrollUntilVisible(page, file)
    await file.scrollIntoViewIfNeeded()
    await page.screenshot({path:join(captures,'attachments-en.png')})
  }
  await removeServerFromMenu(page)
})
