#!/usr/bin/env node
// Generates frontend/src/emoji/data.ts — the emoji set of the Mattermost
// webapp (npm emoji-datasource@6.1.1 + the webapp's
// additional_shortnames.json, see docs/research/2026-09-24-mattermost-api-facts.md
// §7.5) in a compact form: one string per category, one line per emoji —
// "<char> <name> <alias>…" — in the webapp's order. Skin-tone variants are
// not listed: the picker offers the default tone, and emoji/index.ts derives
// toned names for display.
//
// Usage (sources fetched once, the output is committed):
//   node scripts/gen-emoji.mjs <emoji-datasource/emoji.json> <additional_shortnames.json> > frontend/src/emoji/data.ts
import fs from 'node:fs'

const [, , emojiJson, additionalJson] = process.argv
if (!emojiJson || !additionalJson) {
  console.error('usage: node scripts/gen-emoji.mjs <emoji.json> <additional_shortnames.json>')
  process.exit(2)
}
const data = JSON.parse(fs.readFileSync(emojiJson, 'utf8'))
const extra = JSON.parse(fs.readFileSync(additionalJson, 'utf8'))
// emoji-datasource categories in the webapp's order; "Component" (skin tone
// swatches) is not something to pick.
const CATEGORIES = ['Smileys & Emotion', 'People & Body', 'Animals & Nature', 'Food & Drink', 'Travel & Places', 'Activities', 'Objects', 'Symbols', 'Flags']
const char = (unified) => String.fromCodePoint(...unified.split('-').map((h) => parseInt(h, 16)))
const lines = CATEGORIES.map(() => [])
for (const e of [...data].sort((a, b) => a.sort_order - b.sort_order)) {
  const i = CATEGORIES.indexOf(e.category)
  if (i < 0) continue
  lines[i].push([char(e.unified), ...e.short_names, ...(extra[e.short_name] ?? [])].join(' '))
}
process.stdout.write(
  "// Generated by scripts/gen-emoji.mjs from emoji-datasource@6.1.1 and the Mattermost webapp's\n" +
    '// additional_shortnames.json (release-10.11) — do not edit by hand.\n' +
    `const data: readonly string[] = ${JSON.stringify(lines.map((l) => l.join('\n')))}\n` +
    'export default data\n',
)
